name: Test Pin to Providers

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Test [Pinata]
        if: ${{ secrets.PINATA_TEST == "true }}
        uses: ./
        with:
          path: 'dist'
          service: 'pinata'
          pinName: 'ipfs-action'
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}

      - name: Publish Test [Filebase]
        if: ${{ secrets.FILEBASE_TEST == "true }}
        uses: ./
        with:
          path: 'dist'
          service: 'filebase'
          pinName: 'ipfs-action'
          filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
          filebaseKey: ${{ secrets.FILEBASE_KEY }}
          filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

      - name: Publish Test [Infura]
        if: ${{ secrets.INFURA_TEST == "true }}
        uses: ./
        with:
          path: 'dist'
          service: 'pinata'
          pinName: 'ipfs-action'
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}