name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Test [Pinata]
          uses: ./
          with:
            path: 'dist'
            service: 'pinata'
            verbose: true
            pinName: 'ipfs-action'
            pinataKey: ${{ secrets.PINATA_KEY }}
            pinataSecret: ${{ secrets.PINATA_SECRET }}

      - name: Publish Test [Infura]
          uses: ./
          with:
            path: 'dist'
            service: 'pinata'
            verbose: true
            pinName: 'ipfs-action'
            infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
            infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}

      - name: Publish Test [Filebase]
        uses: ./
        with:
          path: 'dist'
          service: 'filebase'
          verbose: true
          pinName: 'ipfs-action'
          filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
          filebaseKey: ${{ secrets.FILEBASE_KEY }}
          filebaseSecret: ${{ secrets.FILEBASE_SECRET }}